import { Router } from "express";
import authRoute from "./auth.routes";
import userRoute from "./user.routes";
import teacherRoute from "./teacher.routes";
import studentRoute from "./student.routes";
import parentRoute from "./parent.routes";
import classroomRoute from "./classroom.routes";
import courseRoute from "./course.routes";
import courseTestRoute from "./coursetest.routes";
import scheduleRoute from "./schedule.routes";
import entranceExamLRRoute from "./entranceExamLR.routes";
import entranceExamRoute from "./entranceExam.routes";
import speakingRoute from "./speaking.routes";
import writingRoute from "./writing.routes";
import teacherPortalRoute from "./teacher.portal.routes";
import enrollmentRoute from "./enrollment.routes";
import paymentRoute from "./payment.routes";
import attendanceRoute from "./attendance.routes";
import seedRoute from "./seed.routes";
import scoreCourseRoute from "./scoreCourse.routes";
import statisticsRoute from "./statistics.routes";
import dashboardRoute from "./dashboard.routes";

const router = Router();

router.use("/auth", authRoute);
router.use("/user", userRoute);
router.use("/teachers", teacherRoute);
router.use("/teacher", teacherPortalRoute);
router.use("/students", studentRoute);
router.use("/parents", parentRoute);
router.use("/classrooms", classroomRoute);
router.use("/courses", courseRoute);
router.use("/course-tests", courseTestRoute);
router.use("/schedule", scheduleRoute);
router.use("/schedules", scheduleRoute);
router.use("/entrance-exam-lr", entranceExamLRRoute);
router.use("/entrance-exam", entranceExamRoute);
router.use("/speaking", speakingRoute);
router.use("/writing", writingRoute);
router.use("/enrollment", enrollmentRoute);
router.use("/payment", paymentRoute);
router.use("/attendance", attendanceRoute);
router.use("/seed", seedRoute);
router.use("/score-courses", scoreCourseRoute);
router.use("/statistics", statisticsRoute);
router.use("/dashboard", dashboardRoute);

export default router;