upstream backend_servers {
    server backend_blue:5000 max_fails=3 fail_timeout=30s;
    server backend_green:5000 max_fails=3 fail_timeout=30s;
}

server {
    listen 80;
    server_name trannam.xyz www.trannam.xyz;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name trannam.xyz www.trannam.xyz;

    resolver 127.0.0.11 valid=30s;

    ssl_certificate /etc/letsencrypt/live/trannam.xyz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/trannam.xyz/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        set $upstream_endpoint http://backend_servers;
        
        proxy_pass $upstream_endpoint;
        
        proxy_next_upstream error timeout http_502 http_503 http_504;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 5s;
        proxy_read_timeout 60s;
    }

    location /uploads/ {
        alias /usr/share/nginx/html/uploads/;
    }
}