name: Deploy English Center

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/english_center
            git pull origin dev
            
            cd frontend
            npm install
            npm run build
            cd ..

            docker-compose up -d --build backend
            docker exec express_api npx prisma migrate deploy
            
            docker image prune -f
